---
# Temporary travis ci file to see travis build
lauguage: minimal
service:
  - docker

env:
  jobs:
    - DISTRO_NAME=ubuntu DISTRO_VERSION=bionic TYPE=base
    - DISTRO_NAME=ubuntu DISTRO_VERSION=bionic TYPE=docker
    - DISTRO_NAME=ubuntu DISTRO_VERSION=bionic TYPE=stress
    - DISTRO_NAME=centos DISTRO_VERSION=7 TYPE=base
    - DISTRO_NAME=centos DISTRO_VERSION=7 TYPE=docker

before_script:
  - make pre-build

scripts:
  - make build-image
